### ISSUE TITLE
Hurdle2 each signal power seems not same 

### ISSUE THREAD

**Issue by koohyunum** [SpectrumCollaborationChallenge/phase1-hurdles#17]
Hi 

In the description of the problem, it says that ...

**_Each signal is present at the same total power as each of the others._** Additive White Gaussian Noise (AWGN) is present in the 3 MHz channel. The signal to noise ratio seen by any individual signal type will be greater than or equal to 15 dB.

But each signal total power is not same.

**Comment by craig-pomeroy** [comment]
The [Entrance Hurdles Problem Description](https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Entrance-Hurdles-Problem-Description.pdf) has been updated to resolve this issue. Specifying both the SNR and total power is redundant for the purposes of this hurdle.
