### ISSUE TITLE
Usage of same packet ports in hurdle_1.py and hurdle_1_rx.py causes an error

### ISSUE THREAD

**Issue by karumugam3** [SpectrumCollaborationChallenge/phase1-hurdles#20]
The default packet port is 9095 in hurdle_1.py. 
9095 is also the default packet port number in hurdle_1_rx.py.

When both scripts are run on different terminals, an error is raised. 
socket.error: [Errno 98] Address already in use

When the packet port number is changed, the applications run smoothly.

**Comment by sodium24** [comment]
FYI it's my understanding that hurdle_1_rx.py is deprecated and the same functionality is now in hurdle_1.py

**Comment by sodium24** [comment]
(See commit 46fb9c6 comments)

**Comment by karumugam3** [comment]
Fixed by the recent commits. Merging the test infrastructure's transmitter and receiver flowgraphs has fixed it. Closing the issue.
