### ISSUE TITLE
Sequence for submitting answer

### ISSUE THREAD

**Issue by koohyunum** [SpectrumCollaborationChallenge/phase1-hurdles#22]
Hi 

In "hurdle2_solution_stub_edited.py" code,

answer is updated during in the function of "__init__()"
    **_self.answer = result_submitter.make_random_guess(sample_filename, num_bins)_**

but at this moment, TCP session is not opened yet, but will open in the main() function
    _**success = result_submitter.submit_my_answer(tb.answer, tb.hurdle2_scoring_host, tb.hurdle2_result_port)**_

This means there is no sample.dat file yet in the solution container when answer is updated.

Is this right?

Thanks.

**Comment by craig-pomeroy** [comment]
The example solution is an example of the mechanics of how to submit your solution, not how to compute that answer. 

I don't know if I'm following your question. Are you asking if you should compute an answer before receiving any samples to process?

**Comment by koohyunum** [comment]
Hi

As the example solution is using make_random_guess when submitting answer, it can submit answer without IQ sample file from Scoring server. 

But for us, we need IQ sample file, but if I want to reuse and change name from make_random_guess() to make_answer() in same location, then 

My question is whether I can change the location of "make_random_guess()" which will be replaced with make_answer() function to be called after TCP session opens. 

Thanks.

**Comment by koohyunum** [comment]
To make clear, 

Here is example solution code for "submit_my_answer"

And this function take "answer" as a parameter. This means we should have already an answer. 

But in this function, it opens TCP socket, and it is ready to receive IQ sample from Scoring Server. 

---------------------------------------------------------------------------------------
def submit_my_answer(answer, host, port):
    success = False
    try:
        # Make socket
        transport = TSocket.TSocket(host, port)
        # Buffering is critical. Raw sockets are very slow
        transport = TTransport.TBufferedTransport(transport)
        # Wrap in a protocol
        protocol = TBinaryProtocol.TBinaryProtocol(transport)
        # Create a client to use the protocol encoder
        # client = Calculator.Client(protocol)
        client = Hurdle2Scoring.Client(protocol)
        # Connect!
        transport.open()
        # send answer to the scoring server
        success = client.submitAnswer(answer)
        # Close!
        transport.close()

    except Thrift.TException as tx:
        print('%s' % tx.message)

    return success

**Comment by craig-pomeroy** [comment]
The function submit_my_answer() does not receive IQ sample from Scoring Server. It submits an answer to the Thrift server running in hurdle2:ScoringServer.py.

Your requirements are to 
1) connect to the TCP server running on the Scoring server on the port defined by --tx-port 
2) process those samples 
3) submit your answer to the Thrift server running on the Scoring server on the port defined by --rpc-port

hurdle2_solution_stub_edited.py is a toy example of steps 1) and 3). 

You may use as much or as little of the code from that example as long as your solution runs according to the command we've specified, can read samples from the Scoring Server via TCP, and return your result in a manner compliant with the Thrift IDL we have provided you.
