### ISSUE TITLE
Hurdle 2 sample length

### ISSUE THREAD

**Issue by ilhaan** [SpectrumCollaborationChallenge/phase1-hurdles#25]
I've tried using the `--sample-duration` option with `run_hurdle2.py` to change the length of generated samples, but this seems to have no effect on the length at all. The generated `samples.dat` is constantly of the same file size too (64K) with different sample duration values. 

Any ideas how to fix this?

**Comment by bpadalino** [comment]
@ilhaan: Are you running the solution as well, or just the tester?  If you don't run the solution, it doesn't run to completion.  Same with Hurdle 1.

**Comment by ilhaan** [comment]
I was running only the scoring container to obtain the generated samples in `sample.dat`. Just tried running this with the solution container as well and it seems to be working fine. Thanks @bpadalino
