### ISSUE TITLE
Issues running the SC2 team-built containers due to uid/gid mismatch

### ISSUE THREAD

**Issue by sodium24** [SpectrumCollaborationChallenge/phase1-hurdles#26]
Containers built with the build scripts on my local machine are working fine, but running those downloaded via s3cmd are having issues. I'm concerned that this could also potentially be an issue for scoring, unless this scenario has already been considered.

Steps:
s3cmd get s3://darpa-sc2-phase1-hurdledownloads/hurdle1/hurdle1_scoring_409e483.tar.bz2 
sudo tar --preserve --same-owner -jxf hurdle1_scoring_409e483.tar.bz2 
(note: I have added preserve and same-owner arguments due to file owner/permission-related failures while running the container when these are not specified)

Now, the owner gid and uid of most files in the extracted container is 165536. My local account uses 100000. I have attempted to change the gid & uid of the files to match, and also have tried creating a new account with gid and uid of 165536. I may be doing something wrong still, but am always running into various errors when running lxc-start. Can you offer any advice for how to run these containers when the gid and uid do not match the local machine's configuration?

**Comment by ilhaan** [comment]
I emailed the SC2 team about this yesterday and they informed me that an updated set of instructions pertaining to compressing a container and running it on a new machine will be uploaded by close of business today.
