### ISSUE TITLE
[Hurdle2} IQ sample is lost

### ISSUE THREAD

**Issue by koohyunum** [SpectrumCollaborationChallenge/phase1-hurdles#27]
Hi

Is there anyone that has issue which IQ samples are not fully transmitted during test is running (1536 bytes are missing - in terms of file size) , but will be fully transferred after test is done?

Here, what I meant for "test" is example code from darpa.

**Comment by craig-pomeroy** [comment]
The file sink block in the the Hurdle 2 Solution Stub defaults to buffered output. If you are not seeing the last set of samples written to disk until the end of the test, that may be why. 

Note that there is no requirement for you to write your samples to disk at all, that behavior was provided for convenience in the solution stub. 

See the [GNU Radio documentation on the file sink block](http://gnuradio.org/doc/sphinx-3.7.0/blocks/file_operators_blk.html) for the function call needed to turn off the file sink's buffering behavior.

**Comment by craig-pomeroy** [comment]
I'll close this issue for now. If you feel that there is a bug in the Hurdle 2 scoring code, please reopen and provide more details on the nature of the bug.
