### ISSUE TITLE
Hurdle 2 FM Signal Bandwidth Overestimated by Signal Generator?

### ISSUE THREAD

**Issue by chadmspooner** [SpectrumCollaborationChallenge/phase1-hurdles#28]
We've generated several sample data sets using the solutions and scoring containers in order to test our Hurdle-2 solution. I've noticed a problem with some of the FM signals. In particular, the correct answer in the signal-generator's information file often overestimates the FM signal bandwidth. Evidence below. I've observed no such overestimation for any of the GMSK or QPSK signals.

The marking of truly unoccupied bins as occupied in the correct answer will penalize our solution. 

As an example, we generated a data file using a random-number generator seed of 215. This produced the sample file and the associated information file. I'll call them samples_215.dat and samples_215.txt. This particular case includes 5 FM signals and one GMSK signal. I've attached a PSD estimate. I've also attached the "correct answer" file samples_215.txt, which indicates that the FM signal near -0.75 MHz occupies three 100-kHz bins. You can see that it barely occupies 1 such bin, even when considering the 99% power occupied bandwidth measure of bandwidth. (See the zoomed-in PSD estimate in the file PSD_estimate_zoom.jpg.)

Each of the two signals on the left edge of the band are also FM, and the samples_215.txt indicates that they have width of 1 100-kHz bin. They are clearly wider than the signal at -0.75 MHz!

![psd_estimate](https://cloud.githubusercontent.com/assets/10657808/20321783/7ad0853e-ab2b-11e6-80bd-4bc797a318a4.jpg)
![psd_estimate_zoom](https://cloud.githubusercontent.com/assets/10657808/20321782/7ace2c8a-ab2b-11e6-8fb5-1af39d7032fe.jpg)
[samples_215.txt](https://github.com/SpectrumCollaborationChallenge/phase1-hurdles/files/592981/samples_215.txt)

**Comment by craig-pomeroy** [comment]
We'll take a look. What did you use for --sample-duration and --fm-file-start?

**Comment by chadmspooner** [comment]
Craig:

sample-duration = 1.0

fm-file-start = 27.75

(Those parameters appear in the file I attached, samples_215.txt.)

Thanks,

Chad

On Tue, 2016-11-15 at 12:13 -0800, craig-pomeroy wrote:
> > We'll take a look. What did you use for --sample-duration and --fm-
file-start? 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/SpectrumC
ollaborationChallenge/phase1-
hurdles","title":"SpectrumCollaborationChallenge/phase1-
hurdles","subtitle":"GitHub repository","main_image_url":"https://clo
ud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-
95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/SpectrumCollaborationChallenge/phas
e1-
hurdles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@craig-
pomeroy in #28: We'll take a look. What did you use for --sample-
duration and --fm-file-start? "}],"action":{"name":"View
Issue","url":"https://github.com/SpectrumCollaborationChallenge/phase
1-hurdles/issues/28#issuecomment-260754135"}}}
-- 
Chad M. Spooner
NorthWest Research Associates
301 Webster Street
Monterey, CA 93940
cmspooner@nwra.com
831 582 4904

**Comment by chadmspooner** [comment]
I see that the bandwidth of the FM signals varies throughout the 1-second file we generated. This is in accordance with the variable bandwidth of the modulating signal in the wav file (a Beethoven symphony I believe). So the FM bins that are "occupied" are a function of time. There is, therefore, no single "correct result" for a long file, although you can ask the containers to create a long file.

**Comment by chadmspooner** [comment]
I suppose this has consequences for the test, especially if any solution temporally segments the input data, processes the segments separately, and then combines the results (I am not saying I do this!). This may lead to a situation in which the solution gets everything right on each segment, but the combination (voting, fusing, what have you) does not match the "correct result". 

Also, the Hurdle 2 description mentions that "each signal in continuous in time and fixed in frequency for the duration of the test vector" and that the solution will be provided "at least 40 msec worth of samples." The more data DARPA provides, the more the FM signals vary in bandwidth, and so are not "fixed in frequency" unless you are only referring to center frequency.

Finally, the Hurdle 2 description states that "each signal occupies an integer number of bins." How can this be guaranteed given the (presumably continuous) variation of the FM signal bandwidth over time?

Classifying the FM signals as FM isn't my concern here. It is with the definition of "occupied bins" relative to the test vector input, since what is marked as occupied or unoccupied is an input to the scoring.

**Comment by haochenku** [comment]
Have similar questions on Hurdle 2. During the test, will Darpa's codes generate FM signal so that it occupy the bin/bins?

**Comment by craig-pomeroy** [comment]
We've posted an update to the [FAQ](https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Threshold-Hurdle-FAQ.pdf)

In short, the FM signal is generated from an actual audio file. 

Answer 22 of the updated FAQ states that the segment of audio will be chosen such that it includes audio with high dynamic range. 

Answer 23 of the updated FAQ states that the answer you provide for the number of occupied bins must be a single aggregate answer, not a series of answers for individual time segments of the transmitted waveform.  

I'll close this topic as these appear to be primarily clarification questions, not bug reports. Please feel free send further clarification questions to SC2@darpa.mil.
