### ISSUE TITLE
Hurdle 2 Inconsistent Designation of Occupied Bins for FM?

### ISSUE THREAD

**Issue by chadmspooner** [SpectrumCollaborationChallenge/phase1-hurdles#29]
We generated a 50-ms sample for Hurdle 2 using the containers.

The associated parameters file indicates that there is an FM signal near -0.85 MHz that occupies three bins and an FM signal near +0.85 MHz that occupies one bin. Here is a PSD analysis of that data using all samples from the 50-ms file:

![psds_seed_856 jpg](https://cloud.githubusercontent.com/assets/10657808/20360015/0b1daade-abe7-11e6-9f53-05e371239347.jpg)

I measured the total power and noise power in the band [-1 -0.7] MHz and also in the single bin [-0.9 -0.8] MHz. This allows the calculation of the signal-only power in the bin and in the three-bin band:

Signal Power in [-0.9 -0.8] MHz = 1177.3
Signal Power in [-1.0 -0.7] MHz = 1217.0
Ratio = 0.967

I repeated this power analysis for the signal at +0.85 MHz:

Signal Power in [0.8 0.9] MHz = 418.5
Signal Power in [0.7 1.0] MHz = 433.6
Ratio = 0.965

So the spectral characteristics are nearly identical, and yet one signal is declared to have three times the bandwidth of the other.  Moreover, the one-bin FM signal has slightly less relative power in the central bin compared to the three-bin FM signal. So if either is to be designated as having bandwidth of more than one bin, it should be the one at +0.85 MHz, not -0.85 MHz. I would think, though, that both of these FM signals would be designated as occupying a single bin.

Is this the intended behavior of the DARPA algorithm for declaring occupied bins for FM?

I've attached the parameters file generated for the seed 856.

[parameters.txt](https://github.com/SpectrumCollaborationChallenge/phase1-hurdles/files/595581/parameters.txt)

**Comment by craig-pomeroy** [comment]
The FAQ states that the audio used for solution evaluation will not be pulled from sections of silence and that it will have high dynamic range. 

With your current set of parameters, you are analyzing a section of audio with minimal dynamic range. That will not produce a representative result.

The DARPA algorithm is not intended to be used with sections of audio such as these. We would suggest either changing the fm_file_start parameter or your sample_duration such that you see a more representative sample of the audio file.

**Comment by haochenku** [comment]
Will DARPA provide us the final test container for hurdle 2 which has enough dynamic range for FM signal?

**Comment by chadmspooner** [comment]
Thanks for the reply. I'm not sure how to evaluate "more representative." I did create further sample data files, selecting both the seed and the fm-start parameter randomly. I find more of the same problems.

For example, here is seed 23 with fm-start set to 140.0. The container says the FM signal near -0.35 MHz spans three bins, and I agree. The container also says the FM signal near +1 MHz spans four bins, but I think it only spans two. 

Signal Power in [0.8, 1.2] MHz = 1826.6
Signal Power in [0.9, 1.1] MHz = 1809.0
Ratio = 0.991

Is this representative? The underlying audio signal is producing an FM signal with over twice the bandwidth of my previous example (those FM signals barely spanned half a bin, these span a full two bins).

![psds_seed_23_140](https://cloud.githubusercontent.com/assets/10657808/20401495/e0b070f2-acad-11e6-8dde-69f4e662ca9d.jpg)

**Comment by craig-pomeroy** [comment]
Please see the updates to https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Threshold-Hurdle-FAQ.pdf for guidance on which sections of the FM audio file are to be considered representative samples.
