### ISSUE TITLE
Hurdle 2 FM bandwidth 

### ISSUE THREAD

**Issue by haochenku** [SpectrumCollaborationChallenge/phase1-hurdles#30]
Hurdle 2 may have a bug on FM signal generation. 
In the Transmitter.py line 102, should it be 
occupied_bw=x['n_bins']*self.bind_width *0.7 ?
Otherwise, if you try to set the fm-file-start = 213 and sample-duration = 3 s, the FM signal will affect the detection of guard band .

**Comment by haochenku** [comment]
To make it more clear, if you run the following command 
'./run_hurdle2.py --fum-file-start=2.127909e2 --instance--seed=3 ' 
you will find that there is no guard bins between GMSK signal (bin: 14) and FM signals(bins: 16,17,18,19). 
![image](https://cloud.githubusercontent.com/assets/6502398/20408534/8c7565dc-acdb-11e6-858b-324b32113110.png)

So there should be a scale parameter 0.7 for FM signal , am I right?

**Comment by chadmspooner** [comment]
Verified. Also, the associated parameter text file indicates the FM signal spans 4 bins, when it actually spans 6.

![psds_seed_3](https://cloud.githubusercontent.com/assets/10657808/20413911/642b5b0a-ace4-11e6-849d-4221642d13b1.jpg)

**Comment by craig-pomeroy** [comment]
Please see the updates to https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Threshold-Hurdle-FAQ.pdf for guidance on which sections of the FM audio file are to be considered representative samples.
