### ISSUE TITLE
LXC containers build but are broken

### ISSUE THREAD

**Issue by aapocketz** [SpectrumCollaborationChallenge/phase1-hurdles#31]
I can run the build scripts to build the image, start the container and SSH in, but when I run the scoring code it is missing dependencies (gnuradio), The containers for hurdle1, 2, 3 all seem to have issues as they seem similar. 

My system is Ubuntu 16.04 x64, perhaps there is a setup issue? Is there a container that is pre-built that I can just test use and customize? 

Is there an alternative way to submit solutions that do not require this fragile container system? I have working solutions that have few outside dependencies other than a few python packages.

**Comment by craig-pomeroy** [comment]
Try running the containers available from our S3 downloads bucket. See here for instructions on how to download them: https://spectrumcollaborationchallenge.com/wp-content/uploads/Downloading-Files-from-S3.pdf

We have had teams successfully build from these build scripts across Ubuntu 14 and Ubuntu 16. There is also a VM that can run the containers available for download from our S3 downloads bucket. 

All submissions must be in the form of LXC containers as specified in our instructions documents. LXC containers will be used in the actual competition as well. 

I'll close this issue for now, but if you cannot run the containers from our darpa-sc2-phase1-hurdledownloads bucket please feel free to reopen.

**Comment by MihailSichitiu** [comment]
I confirm that gnuradio does not work on newly built containers. Even on fresh installs of Ubuntu 16.04, fresh github clone and fresh builds.

**Comment by MihailSichitiu** [comment]
And although downloading the DARPA containers from S3 is fast and painless, they don't start:

farshad@farshad-PowerEdge-R210:~/DARPAContainers/H2$ LXC_PATH=$(pwd)/lxc
farshad@farshad-PowerEdge-R210:~/DARPAContainers/H2$ ls lxc/hurdle2_solution_trusty_lxc/
hurdle2_solution_trusty_lxc.log  metadata.yaml  rootfs
farshad@farshad-PowerEdge-R210:~/DARPAContainers/H2$ lxc-start -P "$LXC_PATH" -n hurdle2_solution_trusty_lxc
lxc-start: tools/lxc_start.c: main: 295 Executing '/sbin/init' with no configuration file may crash the host
farshad@farshad-PowerEdge-R210:~/DARPAContainers/H2$ 

I confirm that both the user and group ids on the container and on the host are the same (1000).

Mihai

**Comment by MihailSichitiu** [comment]
If the containers are named differently, they start if started by root, but then the usernames are all messed up: all files in the sc2 home are owned by ubuntu and cannot be changed, and sc2 cannot sudo:
sc2@h2score:~$ ll
total 24
drwxr-xr-x 3 ubuntu ubuntu 4096 Nov 15 21:11 ./
drwxr-xr-x 4 ubuntu ubuntu 4096 Nov 15 21:11 ../
-rw-r--r-- 1 ubuntu ubuntu  220 Nov 15 21:11 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3637 Nov 15 21:11 .bashrc
drwxr-xr-x 6 ubuntu ubuntu 4096 Nov 15 21:11 phase1-hurdles/
-rw-r--r-- 1 ubuntu ubuntu  675 Nov 15 21:11 .profile
sc2@h2score:~$ sudo bash
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
sc2@h2score:~$ 
These lxc containers are nowhere as cleanly separated from the host and from each other as I hoped they would be.

Mihai
