### ISSUE TITLE
lxd vs lxc

### ISSUE THREAD

**Issue by MihailSichitiu** [SpectrumCollaborationChallenge/phase1-hurdles#34]
I'm sorry, I'm still a little confused of what's going on with lxc vs lxd. 
I finally seem to understand that in the last week we're completely changing the container types from lxc to lxd (which confusingly enough has the command line lxc). Does this mean that all the instructions on building the containers, starting them, getting the IP address, etc, etc in this repository are obsolete? Including the submission instructions that assume lxc containers in the old lxc location?

Mihai

**Comment by craig-pomeroy** [comment]
Hi Mihai,

The instructions have all been updated regarding LXC vs LXD: 

See Section 6 in the hurdle logistics document [here](https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Entrance-Hurdles-Instructions-and-Logistics.pdf) for how to import the scoring containers from the hurdledownloads bucket: 

The S3 upload instructions document [here](https://spectrumcollaborationchallenge.com/wp-content/uploads/Uploading-Solutions-to-S3.pdf) has also been updated.

The instructions include the commands needed to convert your LXC container into a format that LXD can import. 

Please let us know if you have further questions. Closing this for now as this does not appear to be an active bug.

**Comment by MihailSichitiu** [comment]
Well, all the Hurdle Instruction documents are not correct any more, right? I mean, I cannot get the IP address with lxc-info, right? Also, there are no instructions on getting an image out of lxd. I assume there might be an lxc image export, but I'm not sure if that' s what's expected. 

The S3 bucket only has scoring containers and copying them to double them does not work (unique fingerpring).  LXD importing of LXC containers... not sure where that was covered. Maybe I missed it. I apologize if I did. Finally, the instructions for building the containers (lxc? lxd?) by using the script plainly fail now (as far as I can tell the containers they produce are not usable in either).

**Comment by craig-pomeroy** [comment]
The instructions were updated at the same time the new containers were made available, so it should all be internally consistent. 

LXC to LXD is covered in section 4 on the Uploading Solutions to S3 document. 

The Hurdle Logistics document (Section 6) explains how to get IP addresses for containers in LXD. 

Something broke the build scripts over the weekend. As of Monday afternoon, the images that the build scripts download from https://us.images.linuxcontainers.org/ were causing some packages to be unable to install cleanly. We'll be posting an image for you to put into your LXC cache as a workaround for the build scripts shortly.

**Comment by MihailSichitiu** [comment]
Craig,
I can confirm that Saturday morning the images built well, but Sunday they did not anymore, so something is indeed broken. We've been banging our heads with the submission containers since Friday when we were ready with all our software. 

Also, if we use the DARPA S3 containers, the export procedure is different: the images are "imported" by LXD (via the lxc image import) but the submission instructions assume a lxc directory with the metadata.yaml file.
Most instructions referring to containers (if not all! except the ones in here: https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Entrance-Hurdles-Instructions-and-Logistics.pdf ) refer to lxc containers.

**Comment by craig-pomeroy** [comment]
We've posted an older cached LXC image to download_20161114.tar in s3://darpa-sc2-phase1-hurdledownloads

Try moving your cached lxc image to somewhere for backup and replacing it with the image we have on S3.

The cache for each user is located at ~/.cache/lxc.

Move your cache for the download template from ~/.cache/lxc/download 
to something like ~/.cache/lxc/download_old

Download the new tar file from S3 and extract it to your ~/.cache/lxc/

When that's complete and if you've extracted it correctly, you should have a new ~/.cache/lxc/download 
directory. 

If that is the case, try running the build script.

**Comment by MihailSichitiu** [comment]
Craig,

if you know, how do we export an image? I started two containers from the same image, but it seems that changes in one do not propagate in the other one. So which image would be exported by lxc image export? We literally cannot submit if we can't export the image.

Mihai

**Comment by MihailSichitiu** [comment]
I'm even more confused? I didn't think it was possible, but here I am. So, the expectation is not for us to submit an lxd container, but rather a "doctored" lxc container that you'll then be able to import in an lxd container? In other words, we should *not* use the DARPA lxd containers in the S3 DARPA bucket? In which case, why are they there? Confused :-(

**Comment by craig-pomeroy** [comment]
Hi Mihai, 

The LXD containers are provided so you can run your code on your machine against the exact containers we use for scoring. 

We're asking for your containers in an LXD format to avoid having to update the hardcoded file paths in LXC container config files for each hurdle submission. 

Does that help?

**Comment by MihailSichitiu** [comment]
I think that it helped. Let's check. The scoring containers that you'll test our solutions against are LXD containers. Our solutions containers are LXC containers but they were "doctored" to be loadable as an LXD container. Or at least they should be. Somehow I thought that our containers should be "native" LXD containers, not doctored LXC containers. If that's right, we'll work toward this goal.
Thanks,
Mihai

**Comment by craig-pomeroy** [comment]
That's right. All LXD needs to be able to import an image is the root file system (that rootfs directory you tar up when submitting a solution) and a metadata file (metadata.yaml that you include your tar file)

**Comment by MihailSichitiu** [comment]
Thanks, that helps. There is also a mess/conflict with the userid and groupid, which seems to have to be at a certain value for the LXC container to import correctly. Is there any way to check if our LXC containers have that value correctly?

**Comment by craig-pomeroy** [comment]
If you look at the rootfs directory of your container, everything should be owned by 165536.

**Comment by MihailSichitiu** [comment]
The problem is that for us all seems to be owned by root which should have that id, but ls -n gives 0 0 for id and owner?
root@farshad-PowerEdge-R210:~/phase1-hurdles/hurdle1/lxc/hurdle1_solution_trusty_lxc/rootfs# ll
total 84
drwxr-xr-x 21 root root 4096 Nov 20 18:54 ./
drwxrwx---  3 root root 4096 Nov 18 21:34 ../
drwxr-xr-x  2 root root 4096 Nov 18 23:19 bin/
drwxr-xr-x  2 root root 4096 Apr 10  2014 boot/
drwxr-xr-x  3 root root 4096 Oct 28 23:57 dev/
drwxr-xr-x 78 root root 4096 Nov 20 18:57 etc/
drwxr-xr-x  5 root root 4096 Nov 18 20:43 home/
drwxr-xr-x 12 root root 4096 Nov 18 19:57 lib/
drwxr-xr-x  2 root root 4096 Oct 28 23:58 lib64/
drwxr-xr-x  2 root root 4096 Oct 28 23:56 media/
drwxr-xr-x  2 root root 4096 Apr 10  2014 mnt/
drwxr-xr-x  2 root root 4096 Oct 28 23:56 opt/
drwxr-xr-x  2 root root 4096 Apr 10  2014 proc/
drwx------  3 root root 4096 Nov 19 03:26 root/
drwxr-xr-x  8 root root 4096 Nov 18 19:56 run/
drwxr-xr-x  2 root root 4096 Oct 28 23:58 sbin/
drwxr-xr-x  2 root root 4096 Oct 28 23:56 srv/
drwxr-xr-x  2 root root 4096 Mar 12  2014 sys/
drwxrwxrwt  4 root root 4096 Nov 20 18:54 tmp/
drwxr-xr-x 10 root root 4096 Oct 28 23:56 usr/
drwxr-xr-x 11 root root 4096 Oct 28 23:56 var/
root@farshad-PowerEdge-R210:~/phase1-hurdles/hurdle1/lxc/hurdle1_solution_trusty_lxc/rootfs# more /etc/subuid
farshad:165536:65536
lxd:165536:65536
root:165536:65536
root@farshad-PowerEdge-R210:~/phase1-hurdles/hurdle1/lxc/hurdle1_solution_trusty_lxc/rootfs# 

oot@farshad-PowerEdge-R210:~/phase1-hurdles/hurdle1/lxc/hurdle1_solution_trusty_lxc/rootfs# ls -n
total 76
drwxr-xr-x  2 0 0 4096 Nov 18 23:19 bin
drwxr-xr-x  2 0 0 4096 Apr 10  2014 boot
drwxr-xr-x  3 0 0 4096 Oct 28 23:57 dev
drwxr-xr-x 78 0 0 4096 Nov 20 18:57 etc
drwxr-xr-x  5 0 0 4096 Nov 18 20:43 home
drwxr-xr-x 12 0 0 4096 Nov 18 19:57 lib
drwxr-xr-x  2 0 0 4096 Oct 28 23:58 lib64
drwxr-xr-x  2 0 0 4096 Oct 28 23:56 media
drwxr-xr-x  2 0 0 4096 Apr 10  2014 mnt
drwxr-xr-x  2 0 0 4096 Oct 28 23:56 opt
drwxr-xr-x  2 0 0 4096 Apr 10  2014 proc
drwx------  3 0 0 4096 Nov 19 03:26 root
drwxr-xr-x  8 0 0 4096 Nov 18 19:56 run
drwxr-xr-x  2 0 0 4096 Oct 28 23:58 sbin
drwxr-xr-x  2 0 0 4096 Oct 28 23:56 srv
drwxr-xr-x  2 0 0 4096 Mar 12  2014 sys
drwxrwxrwt  4 0 0 4096 Nov 20 18:54 tmp
drwxr-xr-x 10 0 0 4096 Oct 28 23:56 usr
drwxr-xr-x 11 0 0 4096 Oct 28 23:56 var
root@farshad-PowerEdge-R210:~/phase1-hurdles/hurdle1/lxc/hurdle1_solution_trusty_lxc/rootfs#

**Comment by craig-pomeroy** [comment]
It looks like you are running everything as root. You should run the build script as a normal user, specifically the one you configured the setuid, setgid, and lxc profile for.

**Comment by MihailSichitiu** [comment]
Yes, we realized that, that why we started a new server with a clean build on Sunday, but it was too late: lxc containers would not build anymore.
Mihai

**Comment by MihailSichitiu** [comment]
We tried our bziped lxc container against DARPA's lxd container and it passed even with those "bad" userid and groupid. Does it mean that we should be good? This was run on a different server than the one used to make the lxc container (so there should be no "local" dependencies leftovers). Do you think that it's safe to leave it with the current userid and groupid?
Mihai

**Comment by craig-pomeroy** [comment]
We strongly recommend you ensure that your container uses the userids and group ids starting with 165536. If you do not follow with the uid and gid settings we've set in our instructions, we will not be able to ensure your container runs when it is scored.

**Comment by MihailSichitiu** [comment]
If the cache trick works, then it's only a question of time. Which is running short :-(

**Comment by MihailSichitiu** [comment]
Unfortunately the cache trick does not work.
Mihai
