### ISSUE TITLE
Cannot ssh to the container after importing from tar files

### ISSUE THREAD

**Issue by haochenku** [SpectrumCollaborationChallenge/phase1-hurdles#37]
Hi ,
    I am doing a local test to see whether we compressed the container correctly. We have use the latest codes and follows every steps from the instruction. We are now following the instruction in Section 6 in https://spectrumcollaborationchallenge.com/wp-content/uploads/Phase-1-Entrance-Hurdles-Instructions-and-Logistics.pdf 
   We have successfully imported the images and we can use the lxc info command to see the configuration of the compressed containers. However, we cannot ping it using the IP address found.  Do you know how to progress?

**Comment by haochenku** [comment]
the lxc info output the following information:
![image](https://cloud.githubusercontent.com/assets/6502398/20821320/3f1d2928-b807-11e6-8a2a-18938c97d914.png)

**Comment by haochenku** [comment]
If you Ping it, you will get 
![image](https://cloud.githubusercontent.com/assets/6502398/20821344/6f85228c-b807-11e6-8a64-cc240fbde5f9.png)

**Comment by haochenku** [comment]
For your information, I got all the suid correct 
![image](https://cloud.githubusercontent.com/assets/6502398/20821407/d33347dc-b807-11e6-8659-6846c910fc34.png)

**Comment by haochenku** [comment]
Thanks. It seems to be my lxd problem. Even I changed the subuid and subgid, I got an error like ,
![image](https://cloud.githubusercontent.com/assets/6502398/20847213/b3dd98f2-b892-11e6-9335-1d14205f1373.png)
Do you have some suggestions?
Thanks a lot.

**Comment by craig-pomeroy** [comment]
That looks like your LXD network settings are misconfigured in some way. Try re-running 

`sudo lxd init`

and following along in the "Initializing LXD" section of [The LXC configuration instructions](https://github.com/SpectrumCollaborationChallenge/phase1-hurdles/blob/master/LXC_Configuration_Instructions.ipynb)
