### ISSUE TITLE
hurdle 2 questions

### ISSUE THREAD

**Issue by bigtreeyanger** [SpectrumCollaborationChallenge/phase1-hurdles#5]
1. Index of bins is incorrect;
2. When the FM signal is designed to occupy several consecutive bins the generated FM occupy non-contiguous bins instead of contiguous bins, given the way the FM is generated in the source code.
3. When the QPSK signal is designed to occupy, say, 4 bins, the real bandwidth is approximately equivalent to 2 bins, which may or may not be intended?

**Comment by craig-pomeroy** [comment]
These issues should be resolved as of the 11/1 updates.
