### ISSUE TITLE
Hurdle2 refers to hurdle1 code

### ISSUE THREAD

**Issue by dirkcgrunwald** [SpectrumCollaborationChallenge/phase1-hurdles#9]
Line 38 of phase1-hurdles/hurdle2/hurdle2/Transmitter.py does an import of hurdle1
This is used to access tcp_server_sink from hurdle1

In the directions at https://github.com/SpectrumCollaborationChallenge/phase1-hurdles/blob/master/hurdle2/Hurdle%202%20Instructions.ipynb it indicates you should run_hurdle2.py from the phase1-hurdles/hurdle2 directory in the scoring container.

Thus, hurdle1 is not on the path and you get an error such as

Traceback (most recent call last):
  File "./run_hurdle2.py", line 20, in <module>
    from hurdle2.Transmitter import Transmitter
  File "/home/x2go/mnt/phase1-hurdles/hurdle2/hurdle2/Transmitter.py", line 38, in <module>
    import hurdle1
ImportError: No module named hurdle1

**Comment by craig-pomeroy** [comment]
Are you running this from the LXC container built by the hurdle 2 build script? 

That script should have built and installed the hurdle1 code into the same prefix used by GNU Radio, making it available to the Hurdle 2 code. See lines 75 and 76 in build_hurdle_2_trusty.sh for the command used.

Regardless, that's a detail worth mentioning in the code walkthrough docs, I'll make a note of it there.

Please let me know if that resolves your issue.

**Comment by dirkcgrunwald** [comment]
Aha - I was using an old build and didn't completely rebuild the LXC container.
Doing that now -- looks like it will fix it and also answers my question about the
git clone --recursive needed now.

**Comment by craig-pomeroy** [comment]
Great, I'll mark this as closed for now then.
